Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-11, with the labels that each got.

#547 Update ytt tests to better reflect operator worflow
  tests/ytt/external_blobstore_test.go
  tests/ytt/external_db_test.go
  tests/ytt/external_prometheus_metrics_test.go
  tests/ytt/go.mod
  tests/ytt/go.sum
  tests/ytt/missing_attributes_test.go
  tests/ytt/system_registry_test.go
  tests/ytt/uaa_test.go
Labels: in progress

#555 add cf_api_backup_metadata_generator UAA client
  config/capi/capi.yml
  config/get_missing_parameters.star
  config/uaa/uaa.yml
  config/values/20-secrets-config-values.yml
  docs/platform_operators/config-values.md
  hack/generate-values.sh
  sample-cf-install-values.yml
  tests/ytt/missing_attributes_test.go
  tests/ytt/uaa/uaa-values.yml
Labels: in progress

#557 (minor) fix codefence in deploy instructions
  docs/deploy.md
Labels: in progress

#552 add readme for package registry
  docs/platform_operators/system-registry-management.md
Labels: unscheduled

#511 Explore Contour metrics
  docs/platform_operators/networking/networking-metrics-and-monitoring.md
Labels: hacktoberfest-accepted, unscheduled

#434 Validate s3 blobstore
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/pipelines/cf-for-k8s-main.yml
  ci/tasks/create-s3-bucket-data-values-file/task.sh
  ci/tasks/create-s3-bucket-data-values-file/task.yml
  ci/tasks/create-s3-tf-vars-file/task.sh
  ci/tasks/create-s3-tf-vars-file/task.yml
  ci/tasks/run-external-blobstore-validation-test/task.sh
  ci/templates/cf-for-k8s-contributions.yml
  deploy/s3/terraform/blobstore.tf
  deploy/s3/terraform/outputs.tf
  deploy/s3/terraform/provider.tf
  deploy/s3/terraform/variables.tf
Labels: scheduled

#559 fix secret_name for cf_api_backup_metadata_generator client
  config/capi/capi.yml
Labels: in progress

#562 Improve run-cats ci task.
  ci/tasks/run-cats/task.sh
  ci/tasks/run-cats/task.yml
Labels: unscheduled

#565 doc: add transparency to readme banner
  docs/assets/cf-for-k8s-banner.png
Labels: unscheduled

#556 DOC: add playbook and info for maintaining the long-running environment
  docs/maintaining/long-running-environment.md
  docs/platform-availability.md
Labels: in progress

#567 Note that `uaa.database.password` is currently not rotatable
  docs/platform_operators/rotating-secrets-and-certs.md
Labels: unscheduled

#575 Quarks secrets (squashed)
  build/quarks-secret/_vendir/LICENSE
  build/quarks-secret/_vendir/NOTICE
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/.helmignore
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/Chart.yaml
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/README.md
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/NOTES.txt
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/_helpers.tpl
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/cluster-role.yaml
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/crds.yaml
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/operator.yaml
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/templates/service-account.yaml
  build/quarks-secret/_vendir/deploy/helm/quarks-secret/values.yaml
  build/quarks-secret/build.sh
  build/quarks-secret/image-override.yml
  build/quarks-secret/quarks-values.yaml
  config/capi/capi.yml
  config/capi/secrets/quarks-secrets.yml
  config/get_missing_parameters.star
  config/networking/network-policies.yaml
  config/quarks-secret/_ytt_lib/quarks-secret/rendered.yml
  config/quarks-secret/quarks-secret.star
  config/quarks-secret/quarks-secret.yml
  config/system-namespace.yml
  config/uaa/secrets/quarks-secrets.yml
  config/uaa/uaa.yml
  config/values/20-secrets-config-values.yml
  config/values/30-experimental-values.yml
  hack/generate-values.sh
  tests/ytt/capi/capi-values.yml
  tests/ytt/capi_test.go
  tests/ytt/external_prometheus_metrics_test.go
  tests/ytt/go.mod
  tests/ytt/go.sum
  tests/ytt/missing_attributes_test.go
  tests/ytt/quarks_secret/quarks_secret_disabled.yml
  tests/ytt/quarks_secret/quarks_secret_enabled.yml
  tests/ytt/quarks_secret_test.go
  tests/ytt/system_registry_test.go
  tests/ytt/uaa/uaa-values.yml
  tests/ytt/uaa_test.go
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#577 Move Eirini images to cloudfoundry dockerhub
  build/eirini/osl-compliant-image-override.yml
  ci/pipelines/build-eirini-images.yml
  ci/templates/build-eirini-images.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
Labels: in progress

#578 ENH: update to using eirini 2.0 images
  build/eirini/osl-compliant-image-override.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
Labels: in progress

#572 Remove resource requirements also from istio init container
  config/istio/remove-resource-requirements.yml
Labels: in progress

#581 Allow docker auth for smoke tests
  tests/smoke/smoke_test.go
Labels: unscheduled

#582 FIX: Update the eirini image SHAs
  build/eirini/osl-compliant-image-override.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
Labels: unscheduled
