Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-05, with the labels that each got.

#173 STY: improve formatting of bash scripts
  bin/install-cf.sh
  build/eirini/build.sh
  build/minio/build.sh
  build/postgres/build.sh
  config/values.yml
  hack/confirm-network-policy.sh
  hack/generate-values.sh
  hack/run-smoke-tests.sh
Labels: unscheduled

#174 ENH: bump CAPI to current head of master
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccdb-migrate-job.yaml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#162 Remove the install-cf.sh command
  bin/install-cf.sh
  ci/pipelines/cf-for-k8s.yml
  docs/deploy-in-ci.md
  docs/deploy-local.md
  docs/deploy.md
Labels: in progress

#161 Move metacontroller to the build dir and use kbld to pin image to a digest
  build/metacontroller/_vendir/LICENSE
  build/metacontroller/_vendir/manifests/metacontroller-namespace.yaml
  build/metacontroller/_vendir/manifests/metacontroller-rbac.yaml
  build/metacontroller/_vendir/manifests/metacontroller.yaml
  build/metacontroller/build.sh
  config/_ytt_lib/metacontroller/rendered.yml
  config/networking.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#179 Use tls by default for application ingress
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/istio-gateway.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  config/external-routing.yml
  config/gateway.lib.yml
  config/gateway_test.star
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#176 Update deploy instructions
  docs/deploy.md
Labels: in progress

#188 Update deploy docs with updated kapp requirements
  config/0-min-kapp-version.yml
  docs/deploy.md
Labels: in progress

#190 Bump capi-k8s-release
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  config/capi.yml
  config/fix-db-startup-order.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#183 Expose Istio Pilot metrics port in NetworkPolicy
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#191 ENH: add hack script for validating app_registry credentials
  hack/app-registry-check-dockerfile/Dockerfile
  hack/validate-registry-access.sh
Labels: scheduled

#197 Change env variable to fix smoke tests
  docs/contributing.md
Labels: unscheduled

#195 [Bug Fix] cf7 push --strategy rolling shows metrics
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/500-metric-proxy-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#198 MAINT: remove UAA namespace overlay
  config/uaa.yml
Labels: unscheduled

#156 Add validation with kubeval
  config/0-min-kapp-version.yml
  config/kapp-rebase-rules.yml
  tests/configs/configs_test.go
  tests/configs/go.mod
  tests/configs/go.sum
Labels: scheduled

#199 add option to omit hack warning message
  hack/generate-values.sh
Labels: in progress

#201 upgrade logging to 0.2.1
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#202 bump networking images
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#203 Annotate metric-proxy image
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#207 bump capi to pick up api readiness check
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/images.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#211 Update docs for hostname based loadbalancer service
  docs/deploy.md
Labels: in progress

#205 Explicitly define separate system, workloads and internal certs
  config/capi.yml
  config/eirini.yml
  config/uaa.yml
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: in progress
