Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-08, with the labels that each got.

#270 Initial NetworkPolicies for System Components
  config/minio/minio.yml
  config/networking/network-policies.yaml
  config/postgres/postgres.yml
  config/workloads-namespace.yml
  docs/component_authors/networking.md
Labels: scheduled

#334 Revert "Initial NetworkPolicies for System Components"
  config/minio/minio.yml
  config/networking/network-policies.yaml
  config/postgres/postgres.yml
  config/workloads-namespace.yml
  docs/component_authors/networking.md
Labels: unscheduled

#348 Fix status context for external-db pipeline jobs
  ci/pipelines/cf-for-k8s-contributions.yml
Labels: unscheduled

#341 Move UAA encryption keys and login info to secrets
  config/uaa/uaa.yml
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: in progress

#335 Push long lived env sli metric
  ci/pipelines/cf-for-k8s-stability-tests.yml
Labels: in progress

#358 FEAT: speed up deploys by adding kapp ordering for log-cache
  config/kapp-ordering.yml
Labels: unscheduled

#351 Decompose values file into multiple value groupings
  config/capi/capi.yml
  config/minio/minio.yml
  config/uaa/uaa.yml
  config/values.yml
  config/values/00-values.yml
  config/values/10-system-values.yml
  config/values/20-secrets-config-values.yml
Labels: unscheduled

#349 Bump Istio to 1.6.4
  ci/tasks/install-cf-on-kind/task.sh
  config-optional/enable-automount-service-account-token.yml
  config-optional/first-party-jwt-istio.yml
  config-optional/ingressgateway-service-nodeport.yml
  config/kpack/kpack.yml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio-config/app-sidecar.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio-config/control-plane-network-policy.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio/generated/README.md
  config/networking/_ytt_lib/cf-k8s-networking/config/istio/generated/xxx-generated-istio.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
  deploy/kind-on-gcp/install-and-test.sh
  docs/deploy-local.md
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#332 remove duplicate formatting strings
  docs/platform_operators/external-databases.md
Labels: unscheduled

#315 Exploration into using ginkgo to test drive component templates
  tests/ytt/external_db_test.go
  tests/ytt/go.mod
  tests/ytt/go.sum
  tests/ytt/k8s_suite_test.go
  tests/ytt/matchers/namespace_matcher.go
  tests/ytt/matchers/object_meta_matcher.go
  tests/ytt/matchers/produce_yaml_matcher.go
  tests/ytt/matchers/rendering_context.go
  tests/ytt/matchers/secret_matcher.go
  tests/ytt/matchers/throw_error_matcher.go
  tests/ytt/matchers/with_namespace_matcher.go
  tests/ytt/matchers/with_stateful_matcher.go
  tests/ytt/postgres/postgres-values.yml
Labels: unscheduled

#317 Add external database test to cf-for-k8s pipeline
  ci/dockerfiles/cf-for-k8s-ci/Dockerfile
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/pipelines/cf-for-k8s-dev-tooling.yml
  ci/pipelines/cf-for-k8s-main.yml
  ci/tasks/create-rds-tf-vars-file/task.yml
  ci/tasks/delete-rds/task.sh
  ci/tasks/delete-rds/task.yml
  ci/tasks/initialize-rds/task.sh
  ci/tasks/initialize-rds/task.yml
  ci/tasks/install-cf/task.sh
  ci/tasks/install-cf/task.yml
  ci/tasks/install-postgres/task.sh
  ci/templates/cf-for-k8s-contributions.yml
  deploy/rds/terraform/README.md
  deploy/rds/terraform/database.tf
  deploy/rds/terraform/outputs.tf
  deploy/rds/terraform/provider.tf
  deploy/rds/terraform/variables.tf
Labels: in progress

#355 Pass through values for secret names for CAPI
  config/capi/capi.yml
Labels: unscheduled

#364 MAINT: Add eirini image annotation
  build/eirini/osl-compliant-image-override.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
Labels: unscheduled

#367 Add `uaa.clients.cf_api_controllers.secret_name`
  config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/capi/capi.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#366 Remove unused capi secrets
  config/capi/capi.yml
Labels: unscheduled

#337 Update Pull request
  .github/PULL_REQUEST_TEMPLATE.md
Labels: in progress

#327 Add setting to redirect HTTP requests to HTTPS
  config/networking/external-routing.yml
  config/networking/gateway.lib.yml
  config/networking/gateway_test.star
  config/values/00-values.yml
  sample-cf-install-values.yml
Labels: unscheduled

#333 doc: document router access logs for operators
  docs/platform_operators/assets/duration-fields.jpg
  docs/platform_operators/router-access-logs.md
Labels: unscheduled

#336 Re-apply "Initial NetworkPolicies for System Components"
  config/minio/minio.yml
  config/networking/network-policies.yaml
  config/postgres/postgres.yml
  config/workloads-namespace.yml
  docs/component_authors/networking.md
Labels: in progress

#363 Convert optional overlays to config flags
  ci/tasks/install-cf-on-kind/task.sh
  config/eirini/enable-automount-service-account-token.yml
  config/metrics/add-metrics-server-components.yml
  config/metrics/metrics-server-prefer-internal-kubelet-address.yml
  config/networking/ingressgateway-service-nodeport.yml
  config/networking/remove-resource-requirements.yml
  config/networking/use-external-dns-for-wildcard.yml
  config/networking/use-first-party-jwt-tokens.yml
  config/uaa/enable-automount-service-account-token.yml
  config/uaa/remove-resource-requirements.yml
  config/values/00-values.yml
  deploy/kind-on-gcp/install-and-test.sh
  docs/deploy-local.md
  docs/deploy.md
  sample-cf-install-values.yml
  tests/configs/configs_test.go
Labels: in progress

#371 Routing Topology docs
  docs/platform_operators/ingress-routing-topology.md
Labels: in progress

#369 Remove unused uaa.clients.cf_api_controllers.secret
  config/capi/capi.yml
Labels: unscheduled

#379 [WIP] add revision info task at beginning of every job
  ci/configure
  ci/overlays/inject-pipeline-revision.yaml
  ci/overlays/values.yaml
  ci/pipelines/cf-for-k8s-contributions.yml
Labels: unscheduled

#378 Minor pipeline refactoring
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/pipelines/cf-for-k8s-main.yml
  ci/pipelines/cf-for-k8s-stability-tests.yml
  ci/pipelines/cf-for-k8s-upgrade-tests.yml
  ci/pipelines/k8s-pool-management.yml
  ci/tasks/install-cf-on-gke/task.yml
  ci/tasks/install-cf/task.sh
  ci/tasks/install-cf/task.yml
  ci/templates/cf-for-k8s-contributions.yml
Labels: unscheduled

#376 Minor docs grammar fix (it's -> its)
  docs/deploy.md
Labels: unscheduled

#380 Copy routing topology docs assets from cf-k8s-networking repo
  docs/platform_operators/assets/ingress-gateway-topology-directly-to-worker-nodes.jpg
  docs/platform_operators/assets/ingress-gateway-topology-external-lb.jpg
  docs/platform_operators/assets/ingress-gateway-topology-lb-service.jpg
Labels: in progress

#386 UAA bump to v74.24.0
  config/uaa/_ytt_lib/uaa/k8s/templates/deployment.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/encryption_keys.star
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/encryption_keys.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/jwt_policy_signing_keys.star
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/saml_keys.star
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/saml_keys.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/uaa.lib.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/values/_values.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/values/image.yml
  config/uaa/uaa.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#373 Add documentation for configurable properties
  docs/platform_operators/deploy-parameters.md
Labels: unscheduled

#377 bump cf-k8s-networking to include istio 1.6.4 changes
  config/networking/_ytt_lib/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio/generated/xxx-generated-istio.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role-binding.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/service-account.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/values.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#374 Allow blobstore to be configured
  config/capi/capi.yml
  config/minio/minio.yml
  config/values/00-values.yml
  config/values/20-secrets-config-values.yml
  hack/generate-values.sh
Labels: in progress

#382 Add validation test for external database
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/pipelines/cf-for-k8s-main.yml
  ci/tasks/install-cf-on-gke/task.sh
  ci/tasks/run-external-db-validation-test/task.sh
  ci/tasks/run-external-db-validation-test/task.yml
  ci/templates/cf-for-k8s-contributions.yml
Labels: in progress

#392 Renamed the file to better indicate its intention of being a warning …
  docs/platform_operators/warning-regarding-kubectl-usage.md
Labels: in progress

#396 Fix network policies for eirini
  config/networking/network-policies.yaml
Labels: unscheduled

#399 Allow ingress to cf-api-server from eirini-events
  config/networking/network-policies.yaml
Labels: in progress

#400 Updated the description of the log fields emitted by the ingress gateway
  docs/platform_operators/router-access-logs.md
Labels: unscheduled

#401 added reference to envoy docs for `response_flag`
  docs/platform_operators/router-access-logs.md
Labels: in progress

#402 updated description for `upstream_transport_failure_reason`
  docs/platform_operators/router-access-logs.md
Labels: in progress

#404 updated `start_time` description
  docs/platform_operators/router-access-logs.md
Labels: unscheduled

#403 Remove the unused update-gcp-dns hack script
  docs/deploy-in-ci.md
  hack/update-gcp-dns.sh
Labels: unscheduled
