Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-02, with the labels that each got.

#10 Update README
  README.md
Labels: unscheduled

#11 Fix helm command indentation
  README.md
Labels: unscheduled

#14 bump capi-k8s-release
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-configmap.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/namespace.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/nginx-configmap.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/opi-secrets.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#13 remove caBundle empty string configuration to avoid kapp consider it as a change
  build/istio/build.sh
  build/istio/fix-istio-ytt-overlay.yml
  build/istio/overlays.yml
  config/_ytt_lib/istio/all.yml
Labels: in progress

#15 Add script for running smoke tests (& improve feedback on running the smoke tests)
  bin/run-smoke-tests.sh
  tests/smoke/smoke_test.go
Labels: in progress

#18 Add cluster requirements, add additional insructions to deploy docs
  docs/deploy.md
Labels: scheduled

#19 Add logging components
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/100-logging-metadata-service-account.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/300-fluentd-config.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/400-log-cache-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/400-syslog-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/401-istio-destination-rule.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/401-log-cache-virualservice.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/50-secrets.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/500-fluentd-daemonset.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/500-log-cache-deployment.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
  config/logging.yml
  config/values.yml
  hack/generate-values.sh
  vendir.lock.yml
  vendir.yml
Labels: scheduled

#25 docs: Add certificate SAN requirements
  docs/deploy.md
Labels: scheduled

#20 Delete cf org only if it is created
  tests/smoke/smoke_test.go
Labels: scheduled

#21 docs: clarify that the BOSH cli is required for generating values
  docs/deploy.md
Labels: scheduled

#26 fix: put CF vars to unique temp dir
  hack/generate-values.sh
Labels: in progress

#28 Import Istio as part of networking library
  build/istio/build.sh
  build/istio/istio-config.yml
  build/istio/overlays.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/istio-cfrequestcount.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/prometheus-config.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/README.md
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/istio.yml
  config/networking.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#36 Enable faster feedback to PR submitters that a check is pending
  ci/pipelines/cf-for-k8s-prs.yml
Labels: scheduled

#32 Use internal addresses for uaa and capi
  config/networking.yml
Labels: scheduled

#35 feat: ensure traffic on the mesh is encrypted
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/logging.yml
  config/postgres.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#40 bump capi-k8s-release to include log-cache url
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  vendir.lock.yml
  vendir.yml
Labels: scheduled

#44 Bump capi-k8s-release
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-clusterbuilder.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#49 Fix typo in instructions
  docs/deploy.md
Labels: unscheduled
