Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-09, with the labels that each got.

#410 update logging to 0.3.0
  config/logging/_ytt_lib/cf-k8s-logging/300-fluentd-config.yaml
  config/logging/_ytt_lib/cf-k8s-logging/400-log-cache-service.yaml
  config/logging/_ytt_lib/cf-k8s-logging/400-syslog-service.yaml
  config/logging/_ytt_lib/cf-k8s-logging/50-secrets.yaml
  config/logging/_ytt_lib/cf-k8s-logging/500-fluentd-daemonset.yaml
  config/logging/_ytt_lib/cf-k8s-logging/500-log-cache-deployment.yaml
  config/logging/_ytt_lib/cf-k8s-logging/values.yml
  config/logging/logging.yml
  config/values/20-secrets-config-values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#411 Add the Procfile buildpackage to all groups
  config/kpack/default-buildpacks.yml
Labels: in progress

#414 Fix links in docs/maintaining.md
  docs/maintaining.md
Labels: in progress

#413 Remove metric_proxy certs from sample values file
  sample-cf-install-values.yml
Labels: in progress

#415 MAINT: remove metric_proxy cert from values/20-secrets-config-values.yml
  config/values/20-secrets-config-values.yml
Labels: unscheduled

#393 Skip minio installation if external blobstore is configured
  config/kpack/kpack.yml
  config/minio/minio.star
  config/minio/minio.yml
  config/networking/network-policies.yaml
  tests/ytt/blobstore/blobstore-values.yml
  tests/ytt/external_blobstore_test.go
Labels: unscheduled

#394 Add documentation on how to use external blobstores
  docs/deploy.md
  docs/platform_operators/external-blobstore.md
Labels: unscheduled

#405 Validate external blobstore
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/pipelines/cf-for-k8s-main.yml
  ci/tasks/install-cf-on-gke/task.sh
  ci/tasks/install-cf-on-gke/task.yml
  ci/tasks/install-minio/task.sh
  ci/tasks/install-minio/task.yml
  ci/tasks/run-external-blobstore-validation-test/task.sh
  ci/tasks/run-external-blobstore-validation-test/task.yml
  ci/templates/cf-for-k8s-contributions.yml
Labels: unscheduled

#416 Kapp rebase rules
  config/kapp-rebase-rules.yml
Labels: unscheduled

#428 Reorder buildpacks
  config/kpack/default-buildpacks.yml
Labels: unscheduled

#429 Move Istio config and build scripts to cf-for-k8s
  build/istio/build.sh
  build/istio/generate.sh
  build/istio/istioctl-values.yaml
  build/istio/overlays/add-fluent-bit-sidecar-to-ingressgateway.yaml
  build/istio/overlays/add-version-tag.yaml
  build/istio/overlays/ingressgateway-daemonset.yaml
  build/istio/overlays/ingressgateway-drain.yaml
  build/istio/overlays/istio-system-namespace.yaml
  build/istio/overlays/kapp-compatible.yaml
  build/istio/overlays/mtls-mesh-policy.yaml
  build/istio/values.yaml
  config/istio/README.md
  config/istio/add-istio-injection.yml
  config/istio/app-sidecar.yaml
  config/istio/control-plane-network-policy.yaml
  config/istio/external-routing.yml
  config/istio/fluent-bit-ingressgateway-config-map.yaml
  config/istio/gateway.lib.yml
  config/istio/gateway_test.star
  config/istio/ingressgateway-service-nodeport.yml
  config/istio/istio-generated/README.md
  config/istio/istio-generated/xxx-generated-istio.yaml
  config/istio/istio-kapp-ordering.yml
  config/istio/label-istio-ns.yml
  config/istio/peer-auth-fluentd.yaml
  config/istio/remove-resource-requirements.yml
  config/istio/upgrade-istio-sidecars-job.yml
  config/istio/use-external-dns-for-wildcard.yml
  config/istio/use-first-party-jwt-tokens.yml
  config/networking/_ytt_lib/cf-k8s-networking/config/values.yaml
  config/networking/networking.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress, networking

#433 docs: add documentation on sidecar access logs
  docs/platform_operators/assets/sidecar-graph.png
  docs/platform_operators/gateway-access-logs.md
  docs/platform_operators/sidecar-access-logs.md
Labels: in progress

#432 remove capi eirini cert config
  config/capi/capi.yml
Labels: unscheduled

#445 ENH: bump newest supported K8s version from 1.17 to 1.19
  supported_k8s_versions.yml
Labels: unscheduled

#442 updated `duration` field description
  docs/platform_operators/sidecar-access-logs.md
Labels: unscheduled

#441 updated the kubectl command to clarify that users should be using app…
  docs/platform_operators/sidecar-access-logs.md
Labels: unscheduled

#437 cf-for-k8s now uses the latest networking changes
  vendir.lock.yml
  vendir.yml
Labels: networking, unscheduled

#439 Update the sample-cf-install-values.yml blobstore key
  sample-cf-install-values.yml
Labels: unscheduled

#443 documenting upgrade-test results
  docs/testing/uptime-during-platform-upgrades.md
Labels: unscheduled

#454 add additional authorities to cf_api_controllers UAA client
  config/uaa/uaa.yml
Labels: in progress

#406 Make the docs simpler
  docs/deploy.md
Labels: in progress

#458 Update Istio sidecar fluent-bit image
  build/istio/values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
Labels: networking, unscheduled

#430 Use Image Registry for Package Uploads and Secure Internal CF API Endpoints
  ci/tasks/run-external-blobstore-validation-test/task.sh
  config/capi/_ytt_lib/capi-k8s-release/templates/api_server_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cc-kpack-registry-service-account.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/nginx-configmap.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/service.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/eirini/eirini.yml
  config/networking/istio-authorization-policies.yml
  config/networking/network-policies.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#435 remove HPA and fix istiod replicas to 1
  config/istio/remove-hpas-and-scale-istiod.yml
Labels: in progress, networking

#438 Replace namespace data values with internal functions
  config/capi/capi.yml
  config/eirini/eirini.yml
  config/istio/app-sidecar.yaml
  config/istio/external-routing.yml
  config/istio/fluent-bit-ingressgateway-config-map.yaml
  config/istio/gateway.lib.yml
  config/istio/peer-auth-fluentd.yaml
  config/istio/upgrade-istio-sidecars-job.yml
  config/kpack/default-buildpacks.yml
  config/logging/logging.yml
  config/metrics/metrics.yml
  config/namespaces.star
  config/networking/istio-authorization-policies.yml
  config/networking/network-policies.yaml
  config/networking/networking.yml
  config/system-namespace.yml
  config/uaa/uaa.yml
  config/values/10-system-values.yml
  config/workloads-namespace.yml
  tests/ytt/uaa_test.go
Labels: in progress

#448 Bump to latest stable kpack (0.1.2) and latest capi-k8s-release which supports that kpack
  ci/tasks/install-cf-on-kind/only-nodejs-builder-overlay.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/api_server_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cc-kpack-registry-service-account.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccdb-migrate-job.yaml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-controllers-service-account.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-server-service-account.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-worker-service-account.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/clock_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/nginx-configmap.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/periodic-route-sync.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/periodic-sync-crd.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/worker_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/kpack/_ytt_lib/kpack/release-0.1.2.yaml
  config/kpack/default-buildpacks.yml
  config/kpack/kapp-order.yml
  config/kpack/kapp-wait-rules.yml
  config/kpack/kpack.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#463 punctuation
  README.md
Labels: unscheduled

#467 Allow Eirini to hit internal CF API endpoints
  config/networking/istio-authorization-policies.yml
  config/networking/network-policies.yaml
Labels: unscheduled

#468 Tiny: fix markdown mistake in docs
  docs/deploy.md
Labels: unscheduled

#446 add missing namespace labels, harmonize existing labels
  config/capi/staging-ns-label.yml
  config/kpack/kpack-ns-label.yml
  config/minio/minio.yml
  config/networking/network-policies.yaml
  config/postgres/postgres.yml
  config/workloads-namespace.yml
Labels: unscheduled

#477 174962875 eirini image deplab pipeline
  build/eirini/osl-compliant-image-override.yml
  ci/inputs/build-eirini-images.yml
  ci/pipelines/build-eirini-images.yml
  ci/templates/build-eirini-images.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
Labels: unscheduled

#476 doc: cluster requires network policy support
  docs/deploy.md
Labels: unscheduled

#475 Rename allow-istio-control-plane network policy
  config/networking/network-policies.yaml
Labels: networking, unscheduled

#461 Make cc log level configurable
  config/capi/capi.yml
  config/values/00-values.yml
Labels: unscheduled

#480 rename `istio_static_ip` field name to `load_balancer.static_ip`
  ci/pipelines/cf-for-k8s-iaas-tests.yml
  ci/pipelines/cf-for-k8s-stability-tests.yml
  ci/tasks/install-cf-on-gke/task.sh
  ci/tasks/install-cf-on-kind/task.sh
  config/istio/external-routing.yml
  config/istio/ingressgateway-service-nodeport.yml
  config/values/00-values.yml
  docs/deploy-local.md
  docs/platform_operators/deploy-parameters.md
  docs/platform_operators/setup-static-loadbalancer-ip.md
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: unscheduled

#455 Bump Istio to 1.7.1
  build/istio/istioctl-values.yaml
  build/istio/values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
  config/istio/upgrade-istio-sidecars-job.yml
Labels: in progress, networking

#485 FIX: disable_snapshot_annotations to fix #444
  ci/tasks/install-cf-on-kind/only-nodejs-builder-overlay.yml
  ci/tasks/install-cf-on-kind/task.sh
  deploy/kind/cluster.yml
Labels: unscheduled

#484 Document ingress certificate rotation
  docs/platform_operators/rotating-secrets-and-certs.md
Labels: unscheduled
