Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-04, with the labels that each got.

#113 Update capi-k8s-release version for pinning capi images
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#92 Integrates metric-proxy to return app metrics
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/LICENSE
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/100-metric-proxy-service-account.yml
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/400-metric-proxy-service.yml
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/50-metric-proxy-secrets.yml
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/manifests/500-metric-proxy-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/metric-proxy/config/values.yml
  config/capi.yml
  config/metrics.yml
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
  tests/smoke/smoke_test.go
  vendir.lock.yml
  vendir.yml
Labels: in progress

#114 Use a Secret to store DB init credentials
  build/postgres/init-db-values.yml
  config/_ytt_lib/postgres/rendered.yml
  config/postgres.yml
Labels: in progress

#124 Correct DaemonSet spec.updateStrategy
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#125 Make CAPI stats scrapable by prometheus
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#94 Support external-dns and static ip for ingress
  config-optional/use-external-dns-for-wildcard.yml
  config/external-routing.yml
  config/fix-null-annotations.yml
  config/values.yml
  docs/deploy.md
Labels: scheduled

#126 Bump kpack to 0.0.8
  config/_ytt_lib/github.com/pivotal/kpack/release-0.0.8.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#111 Refactor DNS update utility.
  hack/update-gcp-dns.sh
Labels: in progress

#128 bump `cfroutesync` image digest
  config/values.yml
Labels: in progress

#127 Bump capi-k8s-release: fix cf6 push
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#134 1. move registry config one level up 2. update sample install file wi…
  docs/deploy.md
  sample-cf-install-values.yml
Labels: in progress

#135 Remove diego docker flag instruction
  docs/deploy.md
Labels: in progress

#138 Format + add how-to fix
  docs/debugging.md
Labels: scheduled

#139 Update minikube instructions
  docs/deploy-local.md
Labels: in progress

#137 STY: lint deploy.md
  docs/deploy.md
Labels: scheduled

#136 updates for kind users
  config-optional/remove-ingressgateway-service.yml
  config-optional/use-nodeport-for-ingress.yml
  deploy/kind/cluster.yml
  docs/deploy-local.md
Labels: in progress

#150 Add cf-cli version requirements and simplify deploy documentation
  docs/deploy.md
Labels: unscheduled

#152 add retry policy for ccdb-migration job
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccdb-migrate-job.yaml
  config/fix-db-startup-order.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#151 Pin cfroutesync image digest in cf-k8s-networking
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  config/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#160 bump to UAA from 74.16 > 74.17
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/admin_client_credentials.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/_values.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/image.yml
  config/uaa.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#171 update logging to 0.2.0
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/300-fluentd-config.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/400-fluent-ingress-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-fluentd-daemonset.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-log-cache-deployment.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
  config/logging.yml
  config/values.yml
  hack/generate-values.sh
  vendir.lock.yml
  vendir.yml
Labels: in progress

#169 Bump cf-k8s-networking to fix reconcile problem with Route CRD
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled
