Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-03, with the labels that each got.

#39 introduce cf-auth-proxy without tls
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/400-log-cache-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/401-istio-destination-rule.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/401-log-cache-virualservice.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/50-secrets.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/manifests/500-log-cache-deployment.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
  config/logging.yml
  config/values.yml
  hack/generate-values.sh
  vendir.lock.yml
  vendir.yml
Labels: in progress

#52 Upgrade Eirini to v1.3.0
  build/eirini/_vendir/eirini/Chart.yaml
  build/eirini/_vendir/eirini/templates/configmap.yaml
  build/eirini/_vendir/eirini/templates/deployment.yaml
  build/eirini/_vendir/eirini/templates/eirini-pod-security-policy.yaml
  build/eirini/_vendir/eirini/templates/events.yaml
  build/eirini/_vendir/eirini/templates/fluentd-configmap.yaml
  build/eirini/_vendir/eirini/templates/fluentd-daemonset.yaml
  build/eirini/_vendir/eirini/templates/job-secret-smuggler.yaml
  build/eirini/_vendir/eirini/templates/metrics.yaml
  build/eirini/_vendir/eirini/templates/rootfs-patcher.yml
  build/eirini/_vendir/eirini/templates/routing.yaml
  build/eirini/_vendir/eirini/templates/service.yaml
  build/eirini/_vendir/eirini/versions/bits-waiter
  build/eirini/_vendir/eirini/versions/event-reporter
  build/eirini/_vendir/eirini/versions/fluentd
  build/eirini/_vendir/eirini/versions/metrics-collector
  build/eirini/_vendir/eirini/versions/opi
  build/eirini/_vendir/eirini/versions/rootfs-patcher
  build/eirini/_vendir/eirini/versions/route-collector
  build/eirini/_vendir/eirini/versions/route-pod-informer
  build/eirini/_vendir/eirini/versions/route-statefulset-informer
  build/eirini/_vendir/eirini/versions/staging-downloader
  build/eirini/_vendir/eirini/versions/staging-executor
  build/eirini/_vendir/eirini/versions/staging-uploader
  config/_ytt_lib/eirini/rendered.yml
Labels: in progress

#53 Bump UAA to v74.15.0
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/config.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/log4j2.properties
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/metadata.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/service.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/service_account.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/_values.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/image.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/version.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/values/default-values.yml
  config/uaa.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#41 feat: use SDS for ingressgateway cert distribution
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/external-routing.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#50 Add contributors link to main readme
  README.md
Labels: in progress

#54 Adding delete app instruction
  docs/deploy.md
Labels: in progress

#56 use new functionality in ytt to require min ytt version
  config/0-min-version.star
  docs/deploy.md
Labels: in progress

#57 Update remove-resource-requirements.yml
  config-optional/remove-resource-requirements.yml
Labels: in progress

#58 Add option to skip ssl validation to smoke test
  ci/pipelines/cf-for-k8s.yml
  docs/deploy-in-ci.md
  docs/development.md
  tests/smoke/smoke_test.go
Labels: in progress

#62 Use vendir to pull in postgres chart
  build/postgres/_vendir/LICENSE
  build/postgres/_vendir/stable/postgresql/.helmignore
  build/postgres/_vendir/stable/postgresql/Chart.yaml
  build/postgres/_vendir/stable/postgresql/OWNERS
  build/postgres/_vendir/stable/postgresql/README.md
  build/postgres/_vendir/stable/postgresql/ci/default-values.yaml
  build/postgres/_vendir/stable/postgresql/ci/shmvolume-disabled-values.yaml
  build/postgres/_vendir/stable/postgresql/files/README.md
  build/postgres/_vendir/stable/postgresql/files/conf.d/README.md
  build/postgres/_vendir/stable/postgresql/files/docker-entrypoint-initdb.d/README.md
  build/postgres/_vendir/stable/postgresql/templates/NOTES.txt
  build/postgres/_vendir/stable/postgresql/templates/_helpers.tpl
  build/postgres/_vendir/stable/postgresql/templates/configmap.yaml
  build/postgres/_vendir/stable/postgresql/templates/extended-config-configmap.yaml
  build/postgres/_vendir/stable/postgresql/templates/initialization-configmap.yaml
  build/postgres/_vendir/stable/postgresql/templates/metrics-configmap.yaml
  build/postgres/_vendir/stable/postgresql/templates/metrics-svc.yaml
  build/postgres/_vendir/stable/postgresql/templates/networkpolicy.yaml
  build/postgres/_vendir/stable/postgresql/templates/prometheusrule.yaml
  build/postgres/_vendir/stable/postgresql/templates/secrets.yaml
  build/postgres/_vendir/stable/postgresql/templates/serviceaccount.yaml
  build/postgres/_vendir/stable/postgresql/templates/servicemonitor.yaml
  build/postgres/_vendir/stable/postgresql/templates/statefulset-slaves.yaml
  build/postgres/_vendir/stable/postgresql/templates/statefulset.yaml
  build/postgres/_vendir/stable/postgresql/templates/svc-headless.yaml
  build/postgres/_vendir/stable/postgresql/templates/svc-read.yaml
  build/postgres/_vendir/stable/postgresql/templates/svc.yaml
  build/postgres/_vendir/stable/postgresql/values-production.yaml
  build/postgres/_vendir/stable/postgresql/values.schema.json
  build/postgres/_vendir/stable/postgresql/values.yaml
  build/postgres/build.sh
  build/postgres/postgresql/Chart.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#61 specify min required version for vendir
  vendir.yml
Labels: in progress

#64 Update networking release
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/cfroutesync.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#63 Add ability to cf push buildpack apps
  README.md
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-configmap.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/nginx-configmap.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/opi-secrets.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  config/capi.yml
  config/kpack.yml
  config/uaa.yml
  config/values.yml
  docs/deploy-in-ci.md
  docs/deploy-local.md
  docs/deploy.md
  docs/example-app/package.json
  docs/example-app/server.js
  hack/README.md
  hack/confirm-network-policy.sh
  hack/generate-values.sh
  hack/run-smoke-tests.sh
  hack/update-gcp-dns.sh
  sample-cf-install-values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#72 Bump capi-k8s-release with various enhancements
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  config/capi.yml
  config/values.yml
  hack/generate-values.sh
  vendir.lock.yml
  vendir.yml
Labels: in progress

#81 Bump capi to use namespaced kpack `Builder`
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-builder.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-clusterbuilder.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  config/capi.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#85 Bump capi to enable dockerhub use
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#87 bump cf-k8s-logging to 0.1.0
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/100-logging-metadata-service-account.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/300-fluentd-config.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/400-log-cache-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/400-syslog-service.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/401-log-cache-virualservice.yml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/50-secrets.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-fluentd-daemonset.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/500-log-cache-deployment.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-logging/config/values.yml
  config/logging.yml
  config/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#82 Update docs for the new generate-values.sh signature
  docs/deploy.md
Labels: scheduled

#90 Bump capi to label build pods with source_type STG
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#84 Update cf-k8s-networking: IngressGateway Daemonset & NetworkPolicy Fixes
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/external-routing.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#95 Change update-gcp-dns.sh to exclude 'Address' with # in addition to :
  hack/update-gcp-dns.sh
Labels: scheduled
