Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-06, with the labels that each got.

#217 Add docs on how-to setup https
  docs/deploy.md
  docs/setup-ingress-certs-with-letsencrypt.md
Labels: in progress

#214 Replace cfroutesync with routecontroller
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/cfroutesync/crds/routebulksync.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/cfroutesync-configmap.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/cfroutesync-secret.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/cfroutesync.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/istio-cfrequestcount.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/cfroutesync/prometheus-config.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/cluster-role-binding.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/cluster-role.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/routecontroller.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/service-account.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/values.yaml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#215 Add additional namespaces to istio mesh
  config/kpack.yml
  config/networking.yml
Labels: in progress

#219 Adding new istio config folders
  vendir.yml
Labels: scheduled

#218 Rename system certificate secret to cf-system-cert
  config/external-routing.yml
  config/gateway.lib.yml
Labels: in progress

#221 Change docs to use ./tmp instead of /tmp
  .gitignore
  docs/deploy-in-ci.md
  docs/deploy-local.md
  docs/deploy.md
  tmp/.gitignore
Labels: scheduled

#234 bump cf-k8s-networking to v0.2.0
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-config/app-sidecar.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-config/control-plane-network-policy.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio/generated/README.md
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/istio/generated/xxx-generated-istio.yaml
  config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
  config/kpack.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#237 Delete metacontroller
  build/metacontroller/_vendir/LICENSE
  build/metacontroller/_vendir/manifests/metacontroller-namespace.yaml
  build/metacontroller/_vendir/manifests/metacontroller-rbac.yaml
  build/metacontroller/_vendir/manifests/metacontroller.yaml
  build/metacontroller/build.sh
  build/metacontroller/osl-compliant-image-override.yml
  config/_ytt_lib/metacontroller/rendered.yml
  config/networking.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#239 Bump to uaa version 74.21.0
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/ca_certs.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/ca_certs.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/jwt_policy_signing_keys.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/secrets/jwt_policy_signing_keys.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.star
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/uaa.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/_values.yml
  config/_ytt_lib/github.com/cloudfoundry/uaa/k8s/templates/values/image.yml
  config/uaa.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#213 Optionally include metrics-server
  ci/tasks/install-cf-on-kind/task.sh
  config-optional/add-metrics-server-components.yml
  config-optional/patch-metrics-server.yml
  deploy/kind-on-gcp/install-and-test.sh
  docs/deploy-local.md
  docs/deploy.md
  hack/generate-values.sh
  tests/configs/configs_test.go
  tests/configs/go.sum
  vendir.lock.yml
  vendir.yml
Labels: scheduled

#241 Enable tls for external uaa
  config/uaa.yml
  config/values.yml
Labels: scheduled

#248 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: unscheduled

#236 Update instructions for generating real certs
  docs/configuration/setup-ingress-certs-with-letsencrypt.md
Labels: scheduled

#253 Bump capi release
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/api_server_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccdb-migrate-job.yaml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/ccng-config.lib.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-autodetect-builder.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-workloads-staging-namespace.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/clock_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/database-ca-cert-secret.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/service-accounts.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/worker_deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/_default.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/images.yml
  vendir.lock.yml
  vendir.yml
Labels: scheduled

#246 Explicitly copy/paste default scopes for user
  config/uaa.yml
Labels: in progress

#245 Do not install cf-db if external databases are used for capi and uaa
  config/capi.yml
  config/fix-db-startup-order.yml
  config/postgres.star
  config/postgres.yml
  config/uaa.yml
  config/values.yml
Labels: in progress
