Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-10, with the labels that each got.

#482 ENH: Allow operators to provide PEM-encoded certs
  config/eirini/eirini.yml
  config/istio/external-routing.yml
  config/logging/logging.yml
  config/minio/minio.yml
  config/postgres/postgres.yml
  config/uaa/uaa.yml
  config/values/00-values.yml
  config/values/20-secrets-config-values.yml
  docs/platform_operators/deploy-parameters.md
  docs/platform_operators/setup-ingress-certs-with-letsencrypt.md
  hack/generate-values.sh
  sample-cf-install-values.yml
  tests/ytt/uaa/uaa-values.yml
  tests/ytt/uaa_test.go
Labels: unscheduled

#474 add networking metrics docs
  docs/platform_operators/networking-metrics.md
Labels: unscheduled

#464 Expect ingressgateway to be either a Deployment or DaemonSet
  build/istio/istioctl-values.yaml
  config/istio/external-routing.yml
Labels: in progress, networking

#501 ENH: Add SAN definitions to generated certs
  hack/generate-values.sh
Labels: unscheduled

#500 update logging to 0.4.0
  config/logging/logging.yml
  config/networking/network-policies.yaml
  config/values/00-values.yml
  docs/deploy.md
Labels: unscheduled

#495 add option to allow Prometheus scrape access to metrics endpoints
  config/capi/allow-prometheus-metrics-access.yml
  config/metrics/allow-prometheus-metrics-access.yml
  config/uaa/allow-prometheus-metrics-access.yml
  config/values/00-values.yml
  docs/platform_operators/deploy-parameters.md
  sample-cf-install-values.yml
  tests/ytt/blobstore/blobstore-values.yml
  tests/ytt/capi/capi-values.yml
  tests/ytt/external_prometheus_metrics_test.go
  tests/ytt/go.mod
  tests/ytt/go.sum
  tests/ytt/metrics/metrics-values.yml
  tests/ytt/postgres/postgres-values.yml
  tests/ytt/uaa/uaa-values.yml
Labels: unscheduled

#499 doc: required pod capabilities for Istio
  docs/deploy.md
Labels: unscheduled

#497 Use the capi-database-encryption-key-secret in capi-k8s-release
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/secrets.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
  config/capi/capi.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#510 Merge Istio sidecar and app stats
  build/istio/istioctl-values.yaml
Labels: unscheduled

#472 Make application wait for sidecar proxy before starting
  build/istio/istioctl-values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
Labels: networking, unscheduled

#512 Disable prometheus metrics merging
  build/istio/istioctl-values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
Labels: hacktoberfest-accepted

#487 Use full paketo build and run bionic stack images
  ci/tasks/bump-stack/task.sh
  config/kpack/default-buildpacks.yml
Labels: in progress

#514 Use paketo-buildpacks/ruby
  ci/pipelines/cf-for-k8s-contributions.yml
  ci/tasks/bump-buildpacks/task.sh
  ci/tasks/run-cats/task.sh
  ci/templates/cf-for-k8s-contributions.yml
  config/kpack/default-buildpacks.yml
  docs/assets/remove-ruby-buildpack.yml
Labels: unscheduled

#518 Revert "Merge pull request #512 from cloudfoundry/disablePrometheusMerge"
  build/istio/istioctl-values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
Labels: unscheduled

#488 Bump Istio to 1.7.3
  build/istio/values.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
  config/istio/upgrade-istio-sidecars-job.yml
Labels: hacktoberfest-accepted, in progress, networking

#516 reformat version in upgrade job
  build/istio/build.sh
  config/istio/upgrade-istio-sidecars-job.yml
Labels: networking, unscheduled

#522 update logging to 0.5.0
  config/kapp-ordering.yml
Labels: unscheduled

#521 Run Istio Ingressgateway pod as root
  build/istio/overlays/ingressgateway-as-root.yaml
  config/istio/istio-generated/xxx-generated-istio.yaml
Labels: networking, unscheduled

#519 DOC: Update setup-ingress-certs-with-letsencrypt
  docs/platform_operators/setup-ingress-certs-with-letsencrypt.md
Labels: unscheduled

#517 Add private-registry instructions
  config/system-registry.yml
  config/values/00-values.yml
  docs/platform_operators/system-registry.md
  tests/ytt/system-registry/system-registry-values.yml
  tests/ytt/system_registry_test.go
Labels: in progress

#526 Add Scaling documentation
  docs/platform_operators/scaling.md
Labels: in progress

#528 Maint/rm old eirini namespace overlays
  build/eirini/add-namespaces-overlay.yml
  build/eirini/build.sh
  build/eirini/overlays/remove-duplicate-workloads-ns.yml
  build/eirini/overlays/rename-opi-service-name.yml
Labels: in progress

#525 Replace VirtualService with Ingress for routing to system components
  config/capi/capi.yml
  config/ingress.lib.yml
  config/ingress_test.star
  config/istio/external-routing.yml
  config/istio/gateway_test.star
  config/logging/logging.yml
  config/networking/kapp-add-secret-ref-to-ingress.yml
  config/testing_library.star
  config/uaa/uaa.yml
  tests/ytt/external_prometheus_metrics_test.go
  tests/ytt/system_registry_test.go
  tests/ytt/uaa_test.go
Labels: hacktoberfest-accepted, networking, unscheduled

#531 Revert "Replace VirtualService with Ingress for routing to system components"
  config/capi/capi.yml
  config/ingress.lib.yml
  config/ingress_test.star
  config/istio/external-routing.yml
  config/istio/gateway_test.star
  config/logging/logging.yml
  config/networking/kapp-add-secret-ref-to-ingress.yml
  config/testing_library.star
  config/uaa/uaa.yml
  tests/ytt/external_prometheus_metrics_test.go
  tests/ytt/system_registry_test.go
  tests/ytt/uaa_test.go
Labels: unscheduled

#535 171502800 minikube 6cpu 6gbmem
  ci/pipelines/cf-for-k8s-iaas-tests.yml
  ci/tasks/create-minikube-cluster/task.sh
  ci/tasks/create-minikube-cluster/task.yml
  config/capi/capi.yml
  docs/deploy-local.md
Labels: in progress

#534 Bump capi-k8s-release to 29b77b94183a26cefdc98eff5825f22ae6c75090
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  vendir.lock.yml
  vendir.yml
Labels: hacktoberfest-accepted, in progress

#533 ci: add docker app test to smoke tests
  tests/smoke/smoke_test.go
Labels: hacktoberfest-accepted, in progress

#543 DOC: Improve project README
  README.md
  community/MAINTAINERS.md
  docs/assets/architecture.png
  docs/assets/cf-for-k8s-banner.png
Labels: unscheduled

#538 175210100 update secret rotation branch
  ci/pipelines/cf-for-k8s-stability-tests.yml
  docs/platform_operators/rotating-secrets-and-certs.md
Labels: unscheduled

#549 DOCS: add statement to clarify internal database and blobstore usage
  docs/deploy.md
  docs/platform_operators/external-blobstore.md
  docs/platform_operators/external-databases.md
Labels: in progress
