Repository cloudfoundry/cf-for-k8s, pull requests merged in 2020-07, with the labels that each got.

#143 Add documentation how to enable external ccdb und uaadb
  docs/configuration/external-databases.md
  docs/deploy.md
Labels: scheduled

#254 Enable tls for external capi database
  config/capi.yml
  config/values.yml
Labels: scheduled

#247 Apply ssl for system domain workloads
  config/gateway.lib.yml
  config/gateway_test.star
Labels: scheduled

#272 Doc: Rename docs/configuration to docs/platform_operators
  docs/component_authors/.gitkeep
  docs/platform_operators/external-databases.md
  docs/platform_operators/setup-ingress-certs-with-letsencrypt.md
  docs/platform_operators/setup-static-loadbalancer-ip.md
Labels: in progress

#282 FIX: revert CAPI back to 8d1cae7 from Tues 7/7
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/capi-kpack-watcher-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/templates/cf-api-kpack-watcher-deployment.yml
  config/_ytt_lib/github.com/cloudfoundry/capi-k8s-release/values/images.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#285 fix outdated URL in PR-template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: scheduled

#281 Conditionally override UAA SAML config
  config/uaa.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: in progress

#289 Add new secrets
  config/capi.yml
  config/uaa.yml
  config/values.yml
Labels: in progress

#284 Add additional ci-job to validate external database feature
  ci/pipelines/cf-for-k8s.yml
Labels: in progress

#290 Update kubeval timeout threshold
  tests/configs/configs_test.go
Labels: in progress

#292 Refactor postgres into its own directory
  build/postgres/build.sh
  config/fix-db-startup-order.yml
  config/postgres/_ytt_lib/postgres/rendered.yml
  config/postgres/postgres.star
  config/postgres/postgres.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#293 Refactor eirini into its own component directory
  build/eirini/build.sh
  config/eirini/_ytt_lib/eirini/rendered.yml
  config/eirini/eirini.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#294 Refactor minio into its own component directory
  build/minio/build.sh
  ci/tasks/check-vendir-sync/task.sh
  config/minio/_ytt_lib/minio/rendered.yml
  config/minio/minio.yml
  config/minio/must_exist.star
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#295 Use separate secret values for uaa client secrets
  config/capi.yml
  config/uaa.yml
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: unscheduled

#297 Add separate secret for capi cf db encryption key
  config/capi.yml
  config/values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: in progress

#300 Move capi config to its own dir
  config/capi/_ytt_lib/capi-k8s-release/LICENSE
  config/capi/_ytt_lib/capi-k8s-release/templates/api_server_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccdb-migrate-job.yaml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-configmap.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cf-api-kpack-watcher-deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/cf-workloads-staging-namespace.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/clock_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/database-ca-cert-secret.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/deployment_updater_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/nginx-configmap.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/opi-secrets.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/service-accounts.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/service.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/worker_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/capi/capi.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#296 Uaa secrets
  config/uaa.yml
Labels: in progress

#301 Move networking config to its own folder
  config/networking/_ytt_lib/cf-k8s-networking/LICENSE
  config/networking/_ytt_lib/cf-k8s-networking/NOTICE
  config/networking/_ytt_lib/cf-k8s-networking/config/crd/networking.cloudfoundry.org_routes.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/istio-generated/README.md
  config/networking/_ytt_lib/cf-k8s-networking/config/istio-generated/xxx-generated-istio.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role-binding.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/cluster-role.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller-configmap.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/routecontroller.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/routecontroller/service-account.yaml
  config/networking/_ytt_lib/cf-k8s-networking/config/values.yaml
  config/networking/external-routing.yml
  config/networking/gateway.lib.yml
  config/networking/gateway_test.star
  config/networking/networking.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#299 Move to better ytt pattern for encoded overlays
  config/eirini/eirini.yml
Labels: unscheduled

#308 Refactor config
  config/kpack/_ytt_lib/kpack/release-0.0.9.yaml
  config/kpack/default-buildpacks.yml
  config/kpack/kpack.yml
  config/logging/_ytt_lib/cf-k8s-logging/100-logging-metadata-service-account.yaml
  config/logging/_ytt_lib/cf-k8s-logging/300-fluentd-config.yaml
  config/logging/_ytt_lib/cf-k8s-logging/400-fluent-ingress-service.yaml
  config/logging/_ytt_lib/cf-k8s-logging/400-log-cache-service.yaml
  config/logging/_ytt_lib/cf-k8s-logging/400-syslog-service.yaml
  config/logging/_ytt_lib/cf-k8s-logging/401-log-cache-virualservice.yml
  config/logging/_ytt_lib/cf-k8s-logging/50-secrets.yaml
  config/logging/_ytt_lib/cf-k8s-logging/500-fluentd-daemonset.yaml
  config/logging/_ytt_lib/cf-k8s-logging/500-log-cache-deployment.yaml
  config/logging/_ytt_lib/cf-k8s-logging/values.yml
  config/logging/logging.yml
  config/metrics/_ytt_lib/metric-proxy/LICENSE
  config/metrics/_ytt_lib/metric-proxy/config/manifests/100-metric-proxy-service-account.yml
  config/metrics/_ytt_lib/metric-proxy/config/manifests/400-metric-proxy-service.yml
  config/metrics/_ytt_lib/metric-proxy/config/manifests/50-metric-proxy-secrets.yml
  config/metrics/_ytt_lib/metric-proxy/config/manifests/500-metric-proxy-deployment.yml
  config/metrics/_ytt_lib/metric-proxy/config/values.yml
  config/metrics/metrics.yml
  config/uaa/_ytt_lib/uaa/LICENSE
  config/uaa/_ytt_lib/uaa/NOTICE
  config/uaa/_ytt_lib/uaa/k8s/templates/config.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/deployment.star
  config/uaa/_ytt_lib/uaa/k8s/templates/deployment.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/log4j2.properties
  config/uaa/_ytt_lib/uaa/k8s/templates/metadata.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/admin_client_credentials.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/ca_certs.star
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/ca_certs.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/database_credentials.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/jwt_policy_signing_keys.star
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/jwt_policy_signing_keys.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/secrets/smtp_credentials.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/service.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/service_account.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/uaa.lib.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/values/_values.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/values/image.yml
  config/uaa/_ytt_lib/uaa/k8s/templates/values/version.yml
  config/uaa/uaa.yml
  vendir.lock.yml
  vendir.yml
Labels: unscheduled

#313 rename kpack-watcher-client-secret to cf-api-controllers-client-secret
  config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/service-accounts.yml
  config/capi/_ytt_lib/capi-k8s-release/values/_default.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/capi/capi.yml
  config/uaa/uaa.yml
  config/values.yml
  hack/generate-values.sh
  vendir.lock.yml
  vendir.yml
Labels: in progress

#314 MAINT: temporarily use kpack from commit d3004be to unblock CAPI
  config/kpack/_ytt_lib/kpack/kpack-rendered.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#298 Add documentation for external RDS database
  docs/deploy.md
  docs/platform_operators/external-databases.md
Labels: scheduled

#319 Update kpack images
  config/kpack/_ytt_lib/kpack/kpack-rendered.yml
Labels: in progress

#304 allow eirini plaintext communications
  config/capi/_ytt_lib/capi-k8s-release/templates/ccng-config.lib.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/controllers_deployment.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/opi-secrets.yml
  config/capi/_ytt_lib/capi-k8s-release/templates/service-accounts.yml
  config/capi/_ytt_lib/capi-k8s-release/values/images.yml
  config/eirini/eirini.yml
  vendir.lock.yml
  vendir.yml
Labels: scheduled

#325 Correct missing # sign in aws rds example db-values.yml
  docs/platform_operators/external-databases.md
Labels: scheduled

#320 do not kapp version kpack webhook-certs secret
  config/z-kapp-versioned-creds.yml
Labels: scheduled

#291 Add external db check on pr to ci pipeline
  ci/pipelines/cf-for-k8s.yml
  ci/tasks/install-cf-on-gke/task.sh
  ci/tasks/install-cf-on-gke/task.yml
  ci/tasks/install-postgres/task.sh
  ci/tasks/install-postgres/task.yml
Labels: in progress

#328 Add external db check on pr to ci pipeline (second try)
  ci/pipelines/cf-for-k8s.yml
  ci/tasks/install-cf-on-gke/task.sh
  ci/tasks/install-cf-on-gke/task.yml
  ci/tasks/install-postgres/task.sh
  ci/tasks/install-postgres/task.yml
Labels: in progress

#322 update metric-proxy to optional tls release
  config/metrics/_ytt_lib/metric-proxy/100-metric-proxy-service-account.yml
  config/metrics/_ytt_lib/metric-proxy/400-metric-proxy-service.yml
  config/metrics/_ytt_lib/metric-proxy/50-metric-proxy-secrets.yml
  config/metrics/_ytt_lib/metric-proxy/500-metric-proxy-deployment.yml
  config/metrics/_ytt_lib/metric-proxy/LICENSE
  config/metrics/_ytt_lib/metric-proxy/NOTICE
  config/metrics/_ytt_lib/metric-proxy/values.yml
  vendir.lock.yml
  vendir.yml
Labels: in progress

#331 ENH: Add kapp wait rules for kpack resources
  config/kpack/kapp-order.yml
  config/kpack/kapp-wait-rules.yml
Labels: in progress
