Repository cloudfoundry/cf-for-k8s, pull requests merged in 2021-04, with the labels that each got.

#628 ENH: bump Istio from v1.7.3 to v1.8.0
  build/istio/istioctl-values.yaml
  build/istio/values.yaml
  ci/pipelines/cf-k8s-networking-istio-upgrade.yml
  config/istio/istio-generated/xxx-generated-istio.yaml
  config/istio/istio-kapp-ordering.yml
  config/istio/upgrade-istio-sidecars-job.yml
Labels: in progress

#650 ENH: Make Eirini image overrides configurable
  build/eirini/build.sh
  build/eirini/image-override.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
  config/eirini/image-overrides.yml
  config/values/10-eirini-images.yml
Labels: unscheduled

#653 ENH: Make minio images configurable
  config/minio/inject-images.yml
  config/values/10-minio-images.yml
  tests/ytt/external_blobstore_test.go
Labels: unscheduled

#652 ENH: Make istio images configurable
  config/istio/inject-images.yml
  config/values/10-images.yml
  config/values/10-istio-images.yml
Labels: unscheduled

#654 ENH: Make postgres images configurable
  config/postgres/inject-images.yml
  config/values/10-postgres-images.yml
  tests/ytt/external_db_test.go
Labels: unscheduled

#655 Make quarks-secret image configurable with overlay
  build/quarks-secret/build.sh
  build/quarks-secret/image-override.yml
  config/quarks-secret/_ytt_lib/quarks-secret/rendered.yml
  config/quarks-secret/inject-images.yml
  config/values/30-experimental-quarks-images.yml
  config/values/30-experimental-values.yml
Labels: in progress

#656 DOC: Add guidance around cf-for-k8s upgrades
  docs/deploy.md
  docs/platform-availability.md
  docs/platform_operators/README.md
  docs/platform_operators/upgrades.md
Labels: documentation

#658 Remove image override data values
  build/quarks-secret/build.sh
  build/quarks-secret/image-override.yml
  config/eirini/image-overrides.yml
  config/istio/inject-images.yml
  config/minio/inject-images.yml
  config/postgres/inject-images.yml
  config/quarks-secret/_ytt_lib/quarks-secret/rendered.yml
  config/quarks-secret/inject-images.yml
  config/values/10-eirini-images.yml
  config/values/10-istio-images.yml
  config/values/10-minio-images.yml
  config/values/10-postgres-images.yml
  config/values/30-experimental-quarks-images.yml
  config/values/30-experimental-values.yml
  tests/ytt/external_blobstore_test.go
  tests/ytt/external_db_test.go
Labels: unscheduled

#662 Remove eirini-resource-validator
  build/eirini/overlays/remove-resource-validator.yml
  config/eirini/_ytt_lib/eirini/rendered.yml
  config/eirini/eirini.yml
  config/eirini/set-resource-validator-webhook-ca.yml
  config/networking/network-policies.yaml
  config/values/20-secrets-config-values.yml
  hack/generate-values.sh
  sample-cf-install-values.yml
Labels: in progress

#661 Upgrade Istio to 1.9.4
  build/istio/values.yaml
  ci/tasks/generate-release-notes/task.sh
  config/istio/istio-generated/xxx-generated-istio.yaml
  config/istio/upgrade-istio-sidecars-job.yml
Labels: unscheduled
